name: Demo Workflow

on: workflow_dispatch

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout Repo 
          uses: actions/checkout@v4

        - name : Least and Read Files
          run: |
            echo "my 1st job"
            ls -ltr
            cat README.md 

        # - name: Genrate an ASCII Artwork
        #   run: cowsay -f dragon "Hello World" >> sample.txt

    