name: Genrate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout Repo 
          uses: actions/checkout@v4

        - name: Insatll Cowsay
          run: sudo apt-get install cowsay -y

        - name: Execute cowsay command
          run: cowsay -f dragon "Hello World" >> sample.txt

        - name: Check file is present or not
          run: grep -i "dragon" sample.txt

        - name: Read File
          run: cat sample.txt  

        - name : Least and Read Files
          run: ls -ltra
            
            
            

    