name: Genrate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout Repo 
          uses: actions/checkout@v4

        - name: list of files
          run: ls -ltra

        - name: Executing Shell Script
          run: /workspaces/demo-githubactions/.github/workflows
          

        
            
            
            

    