name: Matrix Config

on: 
  #push:
  workflow_dispatch:    

jobs:
  deploy:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, windows-latest]
        image: [hello-world, alpine]
        exclude:
          - image: alpine
            os: windows-latest
        include:
          - image: amd64/alpine
            os: windows-latest    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Echo Docker details
      run: |
        docker info

    - name: Running image on ${{ matrix.os }}
      run: |
        docker run ${{ matrix.image }}
