# name: Matrix Config

# on: push

# jobs:
#     deploy-on-ubuntu:
#         runs-on: ubuntu-latest
#         steps: 
#         - name: Echo docker details, Run Image
#           run: |
#             docker info
#             docker run hello-world

#     deploy-on-windows:
#         runs-on: windows-latest
#         steps: 
#         - name: Echo docker details, Run Image
#           run: |
#             docker info
#             docker run hello-world


name: Matrix Example

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [16, 18]  # Updated Node.js versions
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
