name: Matrix Config

on: push

jobs:
    deploy-on-ubuntu:
        runs-on: ubuntu-latest
        steps: 
        - name: Echo docker details, Run Image
          run: |
            docker info
            docker run hello-word

    deploy-on-windows:
        runs-on: windows-latest
        steps: 
        - name: Echo docker details, Run Image
          run: |
            docker info
            docker run hello-word