name: Secreates in Github Actions

on: 
  schedule:
    - cron: "*/1 * * * *"


env:
    CONTAINER_REGESTIRY: docker.io
    IMAGE_NAME: github-actions-nginx

jobs:
    docker:
        runs-on: ubuntu-latest
        steps: 
        - name: Docker Build, Login, Publish
          run: |
            echo docker build -t ${{ env.CONTAINER_REGESTIRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
            echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
            echo docker push $CONTAINER_REGESTIRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

      
    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps: 
        - name: Docker Run
          run: |
            echo docker run -d -p 8080:80 $CONTAINER_REGESTIRY/${{ env.CONTAINER_REGESTIRY }}/$IMAGE_NAME:latest
            


        