name: Context Testing

on: 
  push:

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo "${{ toJson(github) }}"

      - name: Dump job context
        run: echo "${{ toJson(job) }}"

      - name: Dump steps context
        run: echo "${{ toJson(steps) }}"

      - name: Dump runner context
        run: echo "${{ toJson(runner) }}"

      - name: Dump strategy context
        run: echo "${{ toJson(strategy) }}"

      - name: Dump matrix context
        run: echo "${{ toJson(matrix) }}"

  docker:
    runs-on: ubuntu-latest
    env:
      CONTAINER_REGISTRY: docker.io
      IMAGE_NAME: github-actions-nginx
    steps:
      - name: Docker Build, Login, Publish
        run: |
          docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ env.CONTAINER_REGISTRY }} --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ env.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: docker
    concurrency: 
      group: prod-deployment
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        timeout-minutes: 10
        run: |
          docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
          sleep 600
